"""empty message

Revision ID: 8fb6b3732266
Revises: 3a760ea411cf
Create Date: 2020-07-11 12:20:38.930529

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8fb6b3732266'
down_revision = '3a760ea411cf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('category_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'posts', 'categories', ['category_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'posts', type_='foreignkey')
    op.drop_column('posts', 'category_id')
    # ### end Alembic commands ###
